swagger: "2.0"
info:
  version: 1.0.0
  title: OpenApi Swagger
  license:
    name: MIT
host: ${{ values.repoUrl }}
basePath: /v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths: {}
definitions: {}